version: '3.7'

services:
  users_service:
    build:
      context: ../../.
      dockerfile: docker/operations_service/Dockerfile
      args:
        BUILD_PATH: operations_service
        MIGRATION_PATH: operations_service
        TOKEN: $TOKEN
        USER: $USER
    ports:
      - "11001:11001"
    environment:
      HASH_SALT: "3354961358384ce3a1436527f2825844"
      DB_NAME: "truenorth-db"
      DB_PASS: "pass"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_HOST: "postgres"
      DEBUG: "true"
      ENV: "dev"
      PORT: "11001"
      RUN_MIGRATIONS: "true"
      MIGRATION_PATH: "operations_service"
    networks:
      - default
      - backend
      - postgres_db
networks:
  backend:
    external: true
  postgres_db:
    external: true