version: '3.7'

services:
  operations_service:
    build:
      context: ../../.
      dockerfile: docker/operations_service/Dockerfile
      args:
        BUILD_PATH: operations_service
        MIGRATION_PATH: operations_service
        USER: $USER
    ports:
      - "11002"
    environment:
      DB_NAME: "truenorth_operations_db"
      DB_PASS: "pass"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_HOST: "database_postgres_1"
      DEBUG: "true"
      ENV: "dev"
      PORT: "11002"
      RUN_MIGRATIONS: "true"
      MIGRATION_PATH: "operations_service"
      DEFAULT_USER_BALANCE: "500"
      ADDITION_OPERATION_COST: "1"
      SUBTRACTION_OPERATION_COST: "1"
      DIVISION_OPERATION_COST: "3"
      MULTIPLICATION_OPERATION_COST: "3"
      SQUARE_ROOT_OPERATION_COST: "5"
      RANDOM_STRING_OPERATION_COST: "7"
      USER_CREATED_QUEUE: $USER_CREATED_QUEUE
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
      AWS_REGION: $AWS_REGION
    networks:
      - default
      - backend
      - postgres_db
networks:
  backend:
    external: true
  postgres_db:
    external: true
