version: '3.7'

services:
  users_service:
    build:
      context: ../../.
      dockerfile: docker/users_service/Dockerfile
      args:
        BUILD_PATH: users_service
        MIGRATION_PATH: users_service
        USER: $USER
    ports:
      - "11001:11001"
    environment:
      HASH_SALT: "3354961358384ce3a1436527f2825844"
      DB_NAME: "truenorth_db"
      DB_PASS: "pass"
      DB_PORT: "5432"
      DB_USER: "user"
      DB_HOST: "database_postgres_1"
      DEBUG: "true"
      USER_CREATED_TOPIC_ARN: "topic"
      ENV: "dev"
      PORT: "11001"
      RUN_MIGRATIONS: "true"
      MIGRATION_PATH: "users_service"
    networks:
      - default
      - backend
      - postgres_db
networks:
  backend:
    external: true
  postgres_db:
    external: true