// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_string,optimize_code_size
// @generated from protobuf file "operations/operations_service.proto" (package "pb.operations", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { Balance } from "./structures";
import { Operation } from "./structures";
import { Record } from "./structures";
import { OperationType } from "./structures";
/**
 * @generated from protobuf message pb.operations.OrderBy
 */
export interface OrderBy {
    /**
     * @generated from protobuf field: pb.operations.OrderFieldsEnum orderField = 1;
     */
    orderField: OrderFieldsEnum;
    /**
     * @generated from protobuf field: pb.operations.OrderTypeEnum orderType = 2;
     */
    orderType: OrderTypeEnum;
}
/**
 * @generated from protobuf message pb.operations.ApplyOperationRequest
 */
export interface ApplyOperationRequest {
    /**
     * @generated from protobuf field: pb.operations.OperationType operationType = 1;
     */
    operationType: OperationType;
    /**
     * @generated from protobuf field: repeated double args = 2;
     */
    args: number[];
    /**
     * @generated from protobuf field: int64 userId = 3;
     */
    userId: string;
}
/**
 * @generated from protobuf message pb.operations.ApplyOperationResponse
 */
export interface ApplyOperationResponse {
    /**
     * @generated from protobuf field: pb.operations.Record record = 1;
     */
    record?: Record;
    /**
     * @generated from protobuf field: pb.operations.Operation operation = 2;
     */
    operation?: Operation;
    /**
     * @generated from protobuf field: pb.operations.Balance currentUserBalance = 3;
     */
    currentUserBalance?: Balance;
}
/**
 * @generated from protobuf message pb.operations.GetUserBalanceRequest
 */
export interface GetUserBalanceRequest {
    /**
     * @generated from protobuf field: int64 userId = 1;
     */
    userId: string;
}
/**
 * @generated from protobuf message pb.operations.GetUserBalanceResponse
 */
export interface GetUserBalanceResponse {
    /**
     * @generated from protobuf field: pb.operations.Balance balance = 1;
     */
    balance?: Balance;
}
/**
 * @generated from protobuf message pb.operations.FilterRecordsRequest
 */
export interface FilterRecordsRequest {
    /**
     * @generated from protobuf field: optional int64 userId = 1;
     */
    userId?: string;
    /**
     * @generated from protobuf field: optional int32 limit = 2;
     */
    limit?: number;
    /**
     * @generated from protobuf field: optional int32 page = 3;
     */
    page?: number;
    /**
     * @generated from protobuf field: repeated pb.operations.OrderBy orderByFields = 4;
     */
    orderByFields: OrderBy[];
}
/**
 * @generated from protobuf message pb.operations.FilterRecordsResponse
 */
export interface FilterRecordsResponse {
    /**
     * @generated from protobuf field: repeated pb.operations.Record records = 1;
     */
    records: Record[];
    /**
     * @generated from protobuf field: int64 totalCount = 2;
     */
    totalCount: string;
}
/**
 * @generated from protobuf message pb.operations.DeleteRecordsRequest
 */
export interface DeleteRecordsRequest {
    /**
     * @generated from protobuf field: repeated int64 recordIds = 1;
     */
    recordIds: string[];
    /**
     * @generated from protobuf field: int64 userId = 2;
     */
    userId: string;
}
/**
 * @generated from protobuf message pb.operations.DeleteRecordsResponse
 */
export interface DeleteRecordsResponse {
    /**
     * @generated from protobuf field: repeated pb.operations.Record records = 1;
     */
    records: Record[];
    /**
     * @generated from protobuf field: pb.operations.Balance currentBalance = 2;
     */
    currentBalance?: Balance;
}
/**
 * @generated from protobuf enum pb.operations.OrderTypeEnum
 */
export enum OrderTypeEnum {
    /**
     * @generated from protobuf enum value: ASC = 0;
     */
    ASC = 0,
    /**
     * @generated from protobuf enum value: DESC = 1;
     */
    DESC = 1
}
/**
 * @generated from protobuf enum pb.operations.OrderFieldsEnum
 */
export enum OrderFieldsEnum {
    /**
     * @generated from protobuf enum value: ID = 0;
     */
    ID = 0,
    /**
     * @generated from protobuf enum value: CREATED_AT = 1;
     */
    CREATED_AT = 1,
    /**
     * @generated from protobuf enum value: OPERATION = 2;
     */
    OPERATION = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class OrderBy$Type extends MessageType<OrderBy> {
    constructor() {
        super("pb.operations.OrderBy", [
            { no: 1, name: "orderField", kind: "enum", T: () => ["pb.operations.OrderFieldsEnum", OrderFieldsEnum] },
            { no: 2, name: "orderType", kind: "enum", T: () => ["pb.operations.OrderTypeEnum", OrderTypeEnum] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.OrderBy
 */
export const OrderBy = new OrderBy$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyOperationRequest$Type extends MessageType<ApplyOperationRequest> {
    constructor() {
        super("pb.operations.ApplyOperationRequest", [
            { no: 1, name: "operationType", kind: "enum", T: () => ["pb.operations.OperationType", OperationType] },
            { no: 2, name: "args", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "userId", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.ApplyOperationRequest
 */
export const ApplyOperationRequest = new ApplyOperationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ApplyOperationResponse$Type extends MessageType<ApplyOperationResponse> {
    constructor() {
        super("pb.operations.ApplyOperationResponse", [
            { no: 1, name: "record", kind: "message", T: () => Record },
            { no: 2, name: "operation", kind: "message", T: () => Operation },
            { no: 3, name: "currentUserBalance", kind: "message", T: () => Balance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.ApplyOperationResponse
 */
export const ApplyOperationResponse = new ApplyOperationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserBalanceRequest$Type extends MessageType<GetUserBalanceRequest> {
    constructor() {
        super("pb.operations.GetUserBalanceRequest", [
            { no: 1, name: "userId", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.GetUserBalanceRequest
 */
export const GetUserBalanceRequest = new GetUserBalanceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserBalanceResponse$Type extends MessageType<GetUserBalanceResponse> {
    constructor() {
        super("pb.operations.GetUserBalanceResponse", [
            { no: 1, name: "balance", kind: "message", T: () => Balance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.GetUserBalanceResponse
 */
export const GetUserBalanceResponse = new GetUserBalanceResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FilterRecordsRequest$Type extends MessageType<FilterRecordsRequest> {
    constructor() {
        super("pb.operations.FilterRecordsRequest", [
            { no: 1, name: "userId", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "limit", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "page", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "orderByFields", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => OrderBy }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.FilterRecordsRequest
 */
export const FilterRecordsRequest = new FilterRecordsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FilterRecordsResponse$Type extends MessageType<FilterRecordsResponse> {
    constructor() {
        super("pb.operations.FilterRecordsResponse", [
            { no: 1, name: "records", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Record },
            { no: 2, name: "totalCount", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.FilterRecordsResponse
 */
export const FilterRecordsResponse = new FilterRecordsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteRecordsRequest$Type extends MessageType<DeleteRecordsRequest> {
    constructor() {
        super("pb.operations.DeleteRecordsRequest", [
            { no: 1, name: "recordIds", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "userId", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.DeleteRecordsRequest
 */
export const DeleteRecordsRequest = new DeleteRecordsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteRecordsResponse$Type extends MessageType<DeleteRecordsResponse> {
    constructor() {
        super("pb.operations.DeleteRecordsResponse", [
            { no: 1, name: "records", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Record },
            { no: 2, name: "currentBalance", kind: "message", T: () => Balance }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.operations.DeleteRecordsResponse
 */
export const DeleteRecordsResponse = new DeleteRecordsResponse$Type();
/**
 * @generated ServiceType for protobuf service pb.operations.OperationsService
 */
export const OperationsService = new ServiceType("pb.operations.OperationsService", [
    { name: "ApplyOperation", options: {}, I: ApplyOperationRequest, O: ApplyOperationResponse },
    { name: "GetUserBalance", options: {}, I: GetUserBalanceRequest, O: GetUserBalanceResponse },
    { name: "FilterRecords", options: {}, I: FilterRecordsRequest, O: FilterRecordsResponse },
    { name: "DeleteRecords", options: {}, I: DeleteRecordsRequest, O: DeleteRecordsResponse }
]);
