// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_string,optimize_code_size
// @generated from protobuf file "users/users_service.proto" (package "pb.users", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
import { User } from "./structures";
/**
 * @generated from protobuf message pb.users.CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
}
/**
 * @generated from protobuf message pb.users.CreateUserResponse
 */
export interface CreateUserResponse {
    /**
     * @generated from protobuf field: pb.users.User user = 1;
     */
    user?: User;
}
/**
 * @generated from protobuf message pb.users.GetUserRequest
 */
export interface GetUserRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message pb.users.GetUserResponse
 */
export interface GetUserResponse {
    /**
     * @generated from protobuf field: pb.users.User user = 1;
     */
    user?: User;
}
/**
 * @generated from protobuf message pb.users.GetUserByUsernameRequest
 */
export interface GetUserByUsernameRequest {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
}
/**
 * @generated from protobuf message pb.users.GetUserByUsernameResponse
 */
export interface GetUserByUsernameResponse {
    /**
     * @generated from protobuf field: pb.users.User user = 1;
     */
    user?: User;
}
/**
 * @generated from protobuf message pb.users.DeleteUserRequest
 */
export interface DeleteUserRequest {
    /**
     * @generated from protobuf field: int64 id = 1;
     */
    id: string;
}
/**
 * @generated from protobuf message pb.users.DeleteUserResponse
 */
export interface DeleteUserResponse {
    /**
     * @generated from protobuf field: pb.users.User user = 1;
     */
    user?: User;
}
/**
 * @generated from protobuf message pb.users.CheckUserCredentialsRequest
 */
export interface CheckUserCredentialsRequest {
    /**
     * @generated from protobuf field: string username = 1;
     */
    username: string;
    /**
     * @generated from protobuf field: string password = 2;
     */
    password: string;
}
/**
 * @generated from protobuf message pb.users.CheckUserCredentialsResponse
 */
export interface CheckUserCredentialsResponse {
    /**
     * @generated from protobuf field: pb.users.User user = 1;
     */
    user?: User;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateUserRequest$Type extends MessageType<CreateUserRequest> {
    constructor() {
        super("pb.users.CreateUserRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.CreateUserRequest
 */
export const CreateUserRequest = new CreateUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateUserResponse$Type extends MessageType<CreateUserResponse> {
    constructor() {
        super("pb.users.CreateUserResponse", [
            { no: 1, name: "user", kind: "message", T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.CreateUserResponse
 */
export const CreateUserResponse = new CreateUserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserRequest$Type extends MessageType<GetUserRequest> {
    constructor() {
        super("pb.users.GetUserRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.GetUserRequest
 */
export const GetUserRequest = new GetUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserResponse$Type extends MessageType<GetUserResponse> {
    constructor() {
        super("pb.users.GetUserResponse", [
            { no: 1, name: "user", kind: "message", T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.GetUserResponse
 */
export const GetUserResponse = new GetUserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserByUsernameRequest$Type extends MessageType<GetUserByUsernameRequest> {
    constructor() {
        super("pb.users.GetUserByUsernameRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.GetUserByUsernameRequest
 */
export const GetUserByUsernameRequest = new GetUserByUsernameRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetUserByUsernameResponse$Type extends MessageType<GetUserByUsernameResponse> {
    constructor() {
        super("pb.users.GetUserByUsernameResponse", [
            { no: 1, name: "user", kind: "message", T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.GetUserByUsernameResponse
 */
export const GetUserByUsernameResponse = new GetUserByUsernameResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteUserRequest$Type extends MessageType<DeleteUserRequest> {
    constructor() {
        super("pb.users.DeleteUserRequest", [
            { no: 1, name: "id", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.DeleteUserRequest
 */
export const DeleteUserRequest = new DeleteUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteUserResponse$Type extends MessageType<DeleteUserResponse> {
    constructor() {
        super("pb.users.DeleteUserResponse", [
            { no: 1, name: "user", kind: "message", T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.DeleteUserResponse
 */
export const DeleteUserResponse = new DeleteUserResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckUserCredentialsRequest$Type extends MessageType<CheckUserCredentialsRequest> {
    constructor() {
        super("pb.users.CheckUserCredentialsRequest", [
            { no: 1, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "password", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.CheckUserCredentialsRequest
 */
export const CheckUserCredentialsRequest = new CheckUserCredentialsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckUserCredentialsResponse$Type extends MessageType<CheckUserCredentialsResponse> {
    constructor() {
        super("pb.users.CheckUserCredentialsResponse", [
            { no: 1, name: "user", kind: "message", T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message pb.users.CheckUserCredentialsResponse
 */
export const CheckUserCredentialsResponse = new CheckUserCredentialsResponse$Type();
/**
 * @generated ServiceType for protobuf service pb.users.UserService
 */
export const UserService = new ServiceType("pb.users.UserService", [
    { name: "CheckUserCredentials", options: {}, I: CheckUserCredentialsRequest, O: CheckUserCredentialsResponse },
    { name: "CreateUser", options: {}, I: CreateUserRequest, O: CreateUserResponse },
    { name: "GetUser", options: {}, I: GetUserRequest, O: GetUserResponse },
    { name: "GetUserByUsername", options: {}, I: GetUserByUsernameRequest, O: GetUserByUsernameResponse },
    { name: "DeleteUser", options: {}, I: DeleteUserRequest, O: DeleteUserResponse }
]);
